on:
  push:
    branches:
      - main
jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.20.x]    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Pre Build
        run: |     
          go mod init github.com/felipeksw/tech-challenge-fiap-lambda
          go get -u -v github.com/aws/aws-lambda-go
          env GOOS=linux   
      - name: Build
        working-directory: ./
        run: go build -v -a -work -o cognito-callback 'cmd/cognito-callback/main.go'
      - name: Zip
        working-directory: ./
        run: zip -j cognito-callback.zip cognito-callback
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_GUI }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_GUI }}
          aws-region: us-east-1
      - name: Upload Zip
        working-directory: ./
        run: aws lambda update-function-code --function-name tech-challenge-app-cognito-callback --zip-file fileb://cognito-callback.zip
