on:
  push:
    branches:
      - main
jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - name: check setup
        run: |     
          go mod tidy
      - name: Build
        working-directory: /
        run: go build -v /cmd/cognito-callback/
      - name: Zip
        working-directory: /
        run: zip -j cognito-callback.zip cognito-callback
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Upload Zip
        working-directory: /
        run: aws lambda update-function-code --function-name tech-challenge-app-cognito-callback --zip-file fileb://cognito-callback.zip
